name: Test

on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn test
